### ISSUE TITLE
Inquiry about Project Dependencies and Setup

### ISSUE THREAD

**Issue by sinfone** [dek924/PerX2CT#1]
Hello, I'm really interested in your GitHub project. I've been looking through the repository, but I couldn't find a requirements.txt file. I truly appreciate your work on this project. Could you kindly provide some guidance regarding the dependencies and setup required to run the project successfully? Thank you!

**Comment by dek924** [comment]
Thank you for your interest in the project! 
We have now updated the requirement.txt for setup.
