### ISSUE TITLE
Left / right flip of PA image

### ISSUE THREAD

**Issue by dev000000001** [dek924/PerX2CT#10]
Hi, 

in ./x2ct_nerf/data/base.py why do you left/right flip the PA image?
It was already flipped in ./data_preprocessing/2_xraypro.py before being stored.

Thanks.

**Comment by dek924** [comment]
The `./data_preprocessing/2_xraypro.py` script follows the data preprocessing protocol established by the official X2CT code. It applies a flip to the X-rays, reversing the left and right sides. This step is designed to replicate the conventional X-ray view, simulating how a doctor would see the patient from their perspective, with the left and right sides switched. However, our code includes an additional flip to ensure accurate feature mapping in the 3D space. This is essential for aligning the left and right sides of the image with the actual anatomy of the patient.
