### ISSUE TITLE
Extrinsic camera parameters

### ISSUE THREAD

**Issue by dev000000001** [dek924/PerX2CT#11]
Hi,

Are you using the extrinsic camera parameters of the DRR image as input for perspective rendering?

Thanks

**Comment by dek924** [comment]
In our 2dto3d module, we assign extrinsic camera parameters to their respective views according to the following scheme (`x2ct_nerf/data/base.py`):
```
self.mapping_camera_type2pose = {
    "PA": torch.tensor([0, 0]),  # Posteroanterior view
    "Lateral": torch.tensor([math.pi / 2, math.pi / 2]),  # Lateral view
}
```
This configuration enables us to accurately replicate the camera's position and orientation for various types of  DRR images, including posteroanterior (PA) and lateral views.
