### ISSUE TITLE
Single plane: Is the front of DRR used to generate CT from the model?

### ISSUE THREAD

**Issue by sugartao** [dek924/PerX2CT#12]

**Comment by dek924** [comment]
If you're asking about generating a CT image from a single DRR, then yes, it's common to use a frontal view X-ray for this purpose. Our configuration file, `./configs/PerX2CT_single_input.yaml`, exclusively uses the PA (posteroanterior) view.

**Comment by sugartao** [comment]
Thank you for your reply, then is the model input two identical PA (posteroanterior), or one? This is very important to me. I hope you can reply me. I wish you success in your work and happiness for your family

**Comment by sugartao** [comment]
> If you're asking about generating a CT image from a single DRR, then yes, it's common to use a frontal view X-ray for this purpose. Our configuration file, `./configs/PerX2CT_single_input.yaml`, exclusively uses the PA (posteroanterior) view.

Thank you for your reply, then is the model input two identical PA (posteroanterior), or one? This is very important to me. I hope you can reply me. I wish you success in your work and happiness for your family
