### ISSUE TITLE
FOV

### ISSUE THREAD

**Issue by dev000000001** [dek924/PerX2CT#13]
Why do you have FOV set to 60 in the config file. Shouldn`t this be calculated from the source to detector distance and physical size of the detector?

**Comment by dek924** [comment]
We simulate our 2D to 3D model in reverse to extract 2D synthetic X-rays from 3D CT volumes for various hyperparameters. We determine the our FOV hyperparameter by comparing our 2D synthetic X-rays with Plastimatch outputs, aiming to achieve as close a match as possible.
