### ISSUE TITLE
 #maskFile = fileName + '_outMultiLabelMask' + '.mhd'

### ISSUE THREAD

**Issue by sugartao** [dek924/PerX2CT#14]
What is the mask here? Is it used? Could you explain it in detail? thank you.

**Comment by dek924** [comment]
The mask in the LIDC-IDRI dataset refers to a segmentation mask used to identify nodules within the CT images. However, in our research, we do not use these nodule segmentation masks. We focus on processing the entire CT scan without specifically masking out the nodules.

**Comment by sugartao** [comment]
> The mask in the LIDC-IDRI dataset refers to a segmentation mask used to identify nodules within the CT images. However, in our research, we do not use these nodule segmentation masks. We focus on processing the entire CT scan without specifically masking out the nodules.
Thank you for your reply and good luck with your work
