### ISSUE TITLE
slice_idx

### ISSUE THREAD

**Issue by yransun** [dek924/PerX2CT#15]
Hi,

I am using my own LIDC dataset for training. And my batch_size=1.

Could you please let me know what the "recon_axis, slice_idx" is at https://github.com/dek924/PerX2CT/blob/main/x2ct_nerf/modules/INREncoderZoomAxisInAlign.py#L150?

**Comment by dek924** [comment]
Recon_axis refers to the three anatomical planes of the CT scan: Axial, Coronal, and Sagittal. You can see examples of these planes in Figure 3 of our paper.

Slice_idx indicates the specific slice you want to reconstruct within the CT volume. For example, if the CT volume has a resolution of (128, 128, 128), the slice_idx ranges from 0 to 127. This index specifies which particular slice in the selected plane (recon_axis) you are interested in reconstructing.
