### ISSUE TITLE
Vanilla inference

### ISSUE THREAD

**Issue by samokhinv** [dek924/PerX2CT#16]
Hi! Thank you for your interesting work!

Do you have a script for simple inference - given 2 X-rays (in jpg/dicom format), generate a synthetic CT? 

I would really like to see, what is generated from real X-rays, but I honestly get confused with all data-preprocessing and data-loading steps.

Thanks!

**Comment by SJTUdemon** [comment]
Hi, I have the same question. 
Do you have a script for simple inference now？
Thanks!

**Comment by bttkm82** [comment]
Thank you for showing interest in our research. Unfortunately, we do not plan to carry it out in the near future.
