### ISSUE TITLE
Question about resolution in data preprocessing part.

### ISSUE THREAD

**Issue by Bill-Yang-1** [dek924/PerX2CT#17]
Thanks for your interesting work, but I have some questions I'd like to consult with you.
In your steps 1 and 2, the volume resolution is 320x320x320, and the X-ray image resolution is 320x320. Why does the resolution change to 128x128x128 and 128x128 in steps 3 and 4? Can’t you directly set the resolution to 128 in step 2 when using Plastimatch?

**Comment by dek924** [comment]
Thank you for your interest in our work. The process steps were based on the original work, X2CTGAN (available at https://github.com/kylekma/X2CT). In their method, they first generate synthetic X-rays from a 320x320x320 CT scan, which are then resized to 128x128. Thus, for a fair comparison, we trained using a dataset preprocessed according to their approach.
