### ISSUE TITLE
Data preprocessing. Only part of slices captured.

### ISSUE THREAD

**Issue by waqar-axcelerate** [dek924/PerX2CT#18]
I am trying to run the pre-processing script for this dataset https://zenodo.org/records/8270365 . I ran the pre-processing script on lower limbs in the dataset i.e the whole lower limb, (i.e the both of the legs, pelvis, foot). But the generated x-rays from these ct-scans only capture the foot. What might be the issue for that problem? I believe its related to how in the first script the 0_dicom2mhd.py generates mhd files.

**Comment by bttkm82** [comment]
Our preprocessing code is based on X2CT-GAN (https://github.com/kylekma/X2CT), so we recommend referring to it for further details.

**Comment by waqar-axcelerate** [comment]
So I was able to resolve the issue. In step two of data pre-processing i.e running 1_ctpro_wo_mask.py the dataset is normalized in the z axis in the crop_to_standard function. 
```
def crop_to_standard(scan, scale):
    z, y, x = scan.shape
    if z >= scale:
        ret_scan = scan[z-scale:z, :, :]
    else:
        temp1 = np.zeros(((scale-z)//2, y, x))
        temp2 = np.zeros(((scale-z)-(scale-z)//2, y, x))
        ret_scan = np.concatenate((temp1, scan, temp2), axis=0)
    z, y, x = ret_scan.shape
    if y >= scale:
        ret_scan = ret_scan[:, (y-scale)//2:(y+scale)//2, :]
    else:
        temp1 = np.zeros((z, (scale-y)//2, x))
        temp2 = np.zeros((z, (scale-y)-(scale-y)//2, x))
        ret_scan = np.concatenate((temp1, ret_scan, temp2), axis=1)
    z, y, x = ret_scan.shape
    if x >= scale:
        ret_scan = ret_scan[:, :, (x-scale)//2:(x+scale)//2]
    else:
        temp1 = np.zeros((z, y, (scale-x)//2))
        temp2 = np.zeros((z, y, (scale-x)-(scale-x)//2))
        ret_scan = np.concatenate((temp1, ret_scan, temp2), axis=2)
    return ret_scan
 ```

just change this function, specifically ``` ret_scan = scan[(z//2)-(scale//2):(z//2)+(scale//2), :, :]``` to include the middle slices and the issue was resolved.
