### ISSUE TITLE
A bit question about feature extraction 

### ISSUE THREAD

**Issue by HB-pencil-zero** [dek924/PerX2CT#2]
In ur paper ,  I saw " The local feature map Fvl and the global vector fvg are extracted fromthe third and fourth layer blocks, respectively."But in ur code , it seems the encoder will not change feature layer?   I'm a bit confused about this question. Would u tell me why ?  Thanks for ur goodwork .
![image](https://github.com/dek924/PerX2CT/assets/84109602/87576336-4517-4921-8155-80d8f791931c)

**Comment by dek924** [comment]
It seems that the code you're referring to comes from the 'x2ct_nerf.modules.inr.model.PerspectiveINRNet' module. In this module, only local features are utilized, as specified by the 'PerX2CT' setting, which excludes global features. If you're interested in using both global and local features, please refer to the 'x2ct_nerf.modules.inr.model_global.PerspectiveConcatAfterINRGLNet' code.
