### ISSUE TITLE
Sample data for fast evaluation?

### ISSUE THREAD

**Issue by GesilaA** [dek924/PerX2CT#3]
Thank you for your awesome work! 
I'm very interested in your PerX2CT, but the [LIDC-IDRI](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3041807/) dataset  is over 100G. Could you provide some test samples for fast evaluation?

**Comment by dek924** [comment]
I'm glad you're interested in our PerX2CT. Regarding the LIDC-IDRI dataset, I understand your concerns about its size. Unfortunately, we do not provide direct copies of portions of the dataset, in accordance with the LIDC-IDRI Data's data usage policy. Instead, we recommend downloading only specific samples directly from [this link](https://www.cancerimagingarchive.net/nbia-search/?CollectionCriteria=LIDC-IDRI).
