### ISSUE TITLE
Can u provide processed data?

### ISSUE THREAD

**Issue by HB-pencil-zero** [dek924/PerX2CT#6]
Since we don't have a Windows platform machine, we are unable to use Plastimatch. Or any other ways to process data in linux platform？

**Comment by dek924** [comment]
According to the LIDC-IDRI Data's usage policy, we cannot directly provide processed data. We use Plastimatch on a Windows platform, following previous projects like X2CT-GAN. However, there is also a Linux version of Plastimatch available. You can find installation instructions for the Linux version on the Plastimatch website: [Plastimatch Getting Started Guide](https://plastimatch.org/getting_started.html#:~:text=sudo%20apt%2Dget%20install%20plastimatch). This could be a suitable alternative for processing data on a Linux platform.
