### ISSUE TITLE
Question about monoplanar and biplanar

### ISSUE THREAD

**Issue by Cestovatels** [dek924/PerX2CT#7]
Hello, I have been working on this topic for a while. The question I want to ask is whether I can use your algorithm for biplanar rather than monoplanar. I have a custom dataset. I have a DCM skull and corresponding DCM xray images. However, I want to use only a frontal xray, not a side xray. Is it possible to do this with your algorithm?

Thank you for your answers.

**Comment by sugartao** [comment]
I am also in the related research, can give an email exchange

**Comment by dek924** [comment]
If you have a custom dataset with a folder structure and dataset list similar to ours, you can use only frontal X-rays by making a small modification to the configuration file. I've updated the config file to accommodate single-input scenarios ([configs/PerX2CT_single_input.yaml](https://github.com/dek924/PerX2CT/blob/main/configs/PerX2CT_single_input.yaml)). Please check this for the necessary changes. This modification should allow your algorithm to process frontal X-ray images without requiring side X-rays.

**Comment by Cestovatels** [comment]
> If you have a custom dataset with a folder structure and dataset list similar to ours, you can use only frontal X-rays by making a small modification to the configuration file. I've updated the config file to accommodate single-input scenarios ([configs/PerX2CT_single_input.yaml](https://github.com/dek924/PerX2CT/blob/main/configs/PerX2CT_single_input.yaml)). Please check this for the necessary changes. This modification should allow your algorithm to process frontal X-ray images without requiring side X-rays.

[LIDC-IDRI](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3041807/)
I understand that you are using this folder structure. I'm just asking to be sure.

+ LIDC-IDRI
+   LIDC-IDRI-0001
+      01-01-2000-NA-NA-30178
+        3000566.000000-NA-03192
+          .dcm series      
+      01-01-2000-NA-NA-35511
+        3000923.000000-NA-62357
+        front.dcm xray

**Comment by dek924** [comment]
Yes, the folder structure of the initial dataset (LIDC-IDRI) looks like below:
```
LIDC-IDRI (folder name)
└── LIDC-IDRI-0001 (subject_id)
    └── 3000566.000000-NA-03192 (study uid)
        └── 1-001.dcm 
```
