### ISSUE TITLE
'save_fileName' has no output

### ISSUE THREAD

**Issue by sugartao** [dek924/PerX2CT#8]
```
        dir_names = dir_[len(Folders_Path):].split("/")
        save_fileName = "__".join(dir_names[:-1])  
```

'save_fileName' has no output

**Comment by dek924** [comment]
Please ensure that the structure of your folders matches the assumptions made in our code. Your initial dataset folder should follow the structure shown below:
```
{root_dir}/lidc_idri/manifest-1600709154662/LIDC-IDRI
└── LIDC-IDRI-0001
    └── 3000566.000000-NA-03192
        └── 1-001.dcm
```

In the 0_dicom2mdh.py file, we have specified the Folders_Path and save_path as follows:
```
Folders_Path = f"{root_dir}/lidc_idri/manifest-1600709154662/LIDC-IDRI/"
save_path = f"{root_dir}/lidc_idri/LIDC-IDRI-MDH"
```
You may need to adjust these file paths slightly to ensure that our code can access your data correctly.
